/**
 * Tests for the boot payload contract (brief-443 R7-b, as amended by
 * brief-449 / D-253):
 *
 *   1. `intelligence_brief` delivers a COMPACT brief (D-253 §Change 3) — a
 *      Project State digest + full Risk Flags + full Quality Audit, via a
 *      spec-coupled, fallback-guarded compactor (the INS-249 silent-drop
 *      defect is FIXED, not reintroduced). Reverses R7-b full passthrough.
 *   2. `recent_decisions` cap raised 5 → 15. (R7-b, unchanged.)
 *   3. `guardrails` cap raised 10 → 20. (R7-b, unchanged.)
 *   4. QW-4 prefetch hard cap of 2 removed. (R7-b, unchanged.)
 *   5. Standing rules: Tier A bodies ONLY at boot (D-253 §Change 1 — Tier B
 *      bodies lazy-load via prism_load_rules), plus a Tier B+C index
 *      (`standing_rules_index`, {id,title,tier,topics}) and the deprecated
 *      C-only `standing_rules_tier_c_index` alias, sourced from the R2-B
 *      union read (standing-rules.md ∪ insights.md).
 *
 * Also covers: D-253 §Change 2 in-response oversize tripwire (`response_bytes`
 * + BOOTSTRAP_OVERSIZE), the compactor's spec coupling, and R-intel-SLO — an
 * always-on info diagnostic (`INTEL_SLO`) carrying boot completeness %, brief
 * age vs target, and continuity coverage (log-only; measured on the full
 * pre-compaction brief).
 *
 * Harness: per-test re-import pattern from
 * bootstrap-standing-rules-union.test.ts (mock the GitHub client, capture
 * the registered handler).
 */

process.env.GITHUB_PAT = process.env.GITHUB_PAT || "test-dummy-pat";

import { describe, it, expect, vi, beforeEach } from "vitest";
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";

vi.mock("../src/github/client.js", () => ({
  fetchFile: vi.fn(),
  fetchFiles: vi.fn(),
  pushFile: vi.fn(),
  fileExists: vi.fn(),
  listRepos: vi.fn(),
}));

interface CapturedHandler {
  (args: Record<string, unknown>): Promise<{
    content: Array<{ type: string; text: string }>;
    isError?: boolean;
  }>;
}

interface Diagnostic {
  level: string;
  code: string;
  message: string;
  context?: Record<string, unknown>;
}

const HANDOFF_CONTENT = `# Handoff

## Meta
- Handoff Version: 7
- Session Count: 28
- Template Version: 2.16.0
- Status: Active

## Critical Context
1. Item one

## Where We Are
Working.

## Resumption Point
Pick up.

## Next Steps
1. Do thing A

<!-- EOF: handoff.md -->`;

/** 25 decisions, all SETTLED — exercises both raised caps. */
const DECISIONS_25 =
  "| ID | Title | Domain | Status | Session |\n" +
  "|---|---|---|---|---|\n" +
  Array.from({ length: 25 }, (_, i) => `| D-${i + 1} | Decision ${i + 1} | arch | SETTLED | ${i + 1} |`).join("\n") +
  "\n\n<!-- EOF: _INDEX.md -->";

const TEMPLATE_CONTENT =
  "# Template\nTemplate Version: 2.16.0\nRules.\n<!-- EOF: core-template-mcp.md -->";

/** Full 6-section intelligence brief per the synthesis spec. Age = 28 − 27 = 1 session. */
const FULL_BRIEF = `# Intelligence Brief — prism

> AI-synthesized session intelligence. Generated by Opus at finalization.
> Last synthesized: S27 (2026-06-01)

## Project State
The project is mid-flight on D-240 Phase B with strong momentum.

## Standing Rules & Workflows
INS-30: mirror-pattern divergence creates silent drift bugs.

## Active Operational Knowledge
Operator prefers structured JSON logs and parallel fetches.

## Recent Trajectory
Sessions 25–27 hardened the banner pipeline and landed R2-B.

## Risk Flags
- INS-249: the old compactor matched headers literally.

## Quality Audit
Docs current; task-queue slightly behind session-log.

<!-- EOF: intelligence-brief.md -->`;

/** Tier A rule living in insights.md — proves union sourcing (R3-imm). */
const INSIGHTS_WITH_TIER_A = `# Insights — prism

## Active

### INS-100: Always verify pushes — STANDING RULE [TIER:A]
- Category: operations — **STANDING RULE**
- **Standing procedure:** Re-read after push.

## Formalized

<!-- EOF: insights.md -->
`;

/**
 * Registry with Tier B (topics that do NOT match the opening messages used
 * below) and Tier C rules. Pre-R7-b, neither B rule would have shipped on a
 * topicless boot — that is exactly the behavior this suite proves reversed.
 */
const REGISTRY_B_AND_C = `# Standing Rules — prism

## Active

### INS-201: launchd recovery — STANDING RULE [TIER:B]
- Category: operations — **STANDING RULE**
<!-- topics: launchd -->
- **Standing procedure:** Reload the plist.

### INS-202: untopiced B rule — STANDING RULE [TIER:B]
- Category: operations — **STANDING RULE**
- **Standing procedure:** Applies broadly.

### INS-203: deep audit walkthrough — STANDING RULE [TIER:C]
- Category: reference — **STANDING RULE**
<!-- topics: audit -->
- **Standing procedure:** Long reference body that must NOT ship at boot.

### INS-204: cost reconciliation — STANDING RULE [TIER:C]
- Category: reference — **STANDING RULE**
<!-- topics: cost -->
- **Standing procedure:** Another reference body kept out of the boot payload.

## Formalized

<!-- EOF: standing-rules.md -->
`;

/**
 * D-253 §Change 2: a standing-rules registry large enough to push the boot
 * response past the 100KB hard cap. 60 Tier A rules × ~2KB procedure bodies →
 * ~120KB of `standing_rules` alone, well over the BOOTSTRAP_OVERSIZE threshold.
 * Tier A so the bodies actually ship (only Tier A is delivered post-D-253).
 */
const OVERSIZE_RULES =
  "# Standing Rules — prism\n\n## Active\n\n" +
  Array.from({ length: 60 }, (_, i) => {
    const body = "X".repeat(2000);
    return `### INS-${900 + i}: Oversize rule ${i} — STANDING RULE [TIER:A]\n- Category: operations — **STANDING RULE**\n- **Standing procedure:** ${body}`;
  }).join("\n\n") +
  "\n\n## Formalized\n\n<!-- EOF: standing-rules.md -->\n";

const PREFETCHABLE: Record<string, string> = {
  "architecture.md": "# Architecture\n\n## Stack\nNode.\n\n<!-- EOF: architecture.md -->",
  "known-issues.md": "# Known Issues\n\n## Active\nNone.\n\n<!-- EOF: known-issues.md -->",
  "task-queue.md": "# Task Queue\n\n## Up Next\nThings.\n\n<!-- EOF: task-queue.md -->",
};

function makeFetchFileMock(opts: {
  brief?: string | null;
  insights?: string | null;
  standingRules?: string | null;
  decisions?: string | null;
}): (repo: string, path: string, ref?: string) => Promise<unknown> {
  const ok = (content: string, sha: string) =>
    Promise.resolve({ content, sha, size: content.length });
  const notFound = (repo: string, path: string) =>
    Promise.reject(new Error(`Not found: fetchFile ${repo}/${path}`));

  return (repo: string, path: string) => {
    if (path.endsWith("handoff.md")) return ok(HANDOFF_CONTENT, "h1");
    if (path.endsWith("decisions/_INDEX.md")) {
      if (opts.decisions === null) return notFound(repo, path);
      return ok(opts.decisions ?? DECISIONS_25, "d1");
    }
    if (path.includes("core-template-mcp.md")) return ok(TEMPLATE_CONTENT, "t1");
    if (path.endsWith("intelligence-brief.md")) {
      if (opts.brief === null || opts.brief === undefined) return notFound(repo, path);
      return ok(opts.brief, "b1");
    }
    if (path.endsWith("insights.md")) {
      if (opts.insights === null || opts.insights === undefined) return notFound(repo, path);
      return ok(opts.insights, "i1");
    }
    if (path.endsWith("standing-rules.md")) {
      if (opts.standingRules === null || opts.standingRules === undefined) return notFound(repo, path);
      return ok(opts.standingRules, "sr1");
    }
    for (const [doc, content] of Object.entries(PREFETCHABLE)) {
      if (path.endsWith(doc)) return ok(content, `pf-${doc}`);
    }
    // pending-doc-updates.md, trigger state, trigger.yaml, everything else: absent
    return notFound(repo, path);
  };
}

async function setupBootstrap(opts: {
  brief?: string | null;
  insights?: string | null;
  standingRules?: string | null;
  decisions?: string | null;
}): Promise<CapturedHandler> {
  vi.resetModules();
  vi.clearAllMocks();

  const ghClient = await import("../src/github/client.js");
  vi.mocked(ghClient.fetchFile).mockImplementation(
    makeFetchFileMock(opts) as never,
  );
  vi.mocked(ghClient.pushFile).mockResolvedValue({
    success: true,
    sha: "pushed",
    size: 100,
  });
  vi.mocked(ghClient.fetchFiles).mockResolvedValue({
    files: new Map(),
    failed: [],
    incomplete: false,
  });
  vi.mocked(ghClient.fileExists).mockResolvedValue(false);
  vi.mocked(ghClient.listRepos).mockResolvedValue([]);

  let captured: CapturedHandler | null = null;
  const mockServer = {
    tool: vi.fn(
      (name: string, _desc: string, _schema: unknown, handler: unknown) => {
        if (name === "prism_bootstrap") {
          captured = handler as CapturedHandler;
        }
      },
    ),
  } as unknown as McpServer;

  const { registerBootstrap } = await import("../src/tools/bootstrap.js");
  registerBootstrap(mockServer);
  if (!captured) throw new Error("prism_bootstrap handler was not registered");
  return captured;
}

async function boot(
  handler: CapturedHandler,
  openingMessage?: string,
): Promise<Record<string, any>> {
  const result = await handler({
    project_slug: "prism",
    ...(openingMessage !== undefined ? { opening_message: openingMessage } : {}),
  });
  expect(result.isError).toBeFalsy();
  return JSON.parse(result.content[0].text);
}

beforeEach(() => {
  process.env.TRIGGER_AUTO_ENROLL = "false";
});

// ── D-253 §Change 3: compacted intelligence brief (R7-b full passthrough reversed) ─

describe("D-253: intelligence_brief delivers the COMPACT brief (Project State digest + full Risk Flags + full Quality Audit)", () => {
  it("emits the compact Project State digest plus the full Risk Flags and Quality Audit sections", async () => {
    const handler = await setupBootstrap({
      brief: FULL_BRIEF,
      insights: INSIGHTS_WITH_TIER_A,
      standingRules: REGISTRY_B_AND_C,
    });
    const parsed = await boot(handler);

    // Compact digest marker + the Project State sentence it summarizes.
    expect(parsed.intelligence_brief).toContain("**Project State (compact):**");
    expect(parsed.intelligence_brief).toContain(
      "The project is mid-flight on D-240 Phase B with strong momentum.",
    );
    // The two full-passthrough sections survive intact (header + body).
    expect(parsed.intelligence_brief).toContain("## Risk Flags");
    expect(parsed.intelligence_brief).toContain(
      "- INS-249: the old compactor matched headers literally.",
    );
    expect(parsed.intelligence_brief).toContain("## Quality Audit");
    expect(parsed.intelligence_brief).toContain(
      "Docs current; task-queue slightly behind session-log.",
    );
  });

  it("drops the three middle sections (and their bodies) that compaction does not carry", async () => {
    const handler = await setupBootstrap({ brief: FULL_BRIEF, insights: null, standingRules: null });
    const parsed = await boot(handler);

    expect(parsed.intelligence_brief).not.toContain("## Standing Rules & Workflows");
    expect(parsed.intelligence_brief).not.toContain("## Active Operational Knowledge");
    expect(parsed.intelligence_brief).not.toContain("## Recent Trajectory");
    expect(parsed.intelligence_brief).not.toContain(
      "mirror-pattern divergence creates silent drift bugs",
    );
    expect(parsed.intelligence_brief).not.toContain("Operator prefers structured JSON logs");
  });

  it("carries the compaction marker and is shorter than the full brief", async () => {
    const handler = await setupBootstrap({ brief: FULL_BRIEF, insights: null, standingRules: null });
    const parsed = await boot(handler);

    expect(parsed.intelligence_brief).toContain("(compact)");
    expect(parsed.intelligence_brief.length).toBeLessThan(FULL_BRIEF.length);
  });

  it("intelligence_brief is null when the document is absent (unchanged contract)", async () => {
    const handler = await setupBootstrap({ brief: null, insights: null, standingRules: null });
    const parsed = await boot(handler);
    expect(parsed.intelligence_brief).toBeNull();
  });

  it("brief_age_sessions still parses from the full brief preamble (staleness reads pre-compaction content)", async () => {
    const handler = await setupBootstrap({ brief: FULL_BRIEF, insights: null, standingRules: null });
    const parsed = await boot(handler);
    // Session Count 28, Last synthesized S27 → age 1. The "Last synthesized:"
    // header lives in the preamble compaction drops, so a correct age proves
    // staleness reads the full content, not the compacted delivery.
    expect(parsed.brief_age_sessions).toBe(1);
  });

  it("falls back to FULL passthrough + BRIEF_COMPACT_FALLBACK when a consumed section is missing (INS-249 silent-drop guard)", async () => {
    // Rename the Risk Flags header so the compactor cannot find it. The fix for
    // the INS-249 defect: rather than silently shrinking the brief, deliver it
    // in full and flag the gap by name.
    const missingRiskFlags = FULL_BRIEF.replace("## Risk Flags", "## Risks");
    const handler = await setupBootstrap({ brief: missingRiskFlags, insights: null, standingRules: null });
    const parsed = await boot(handler);

    // Full passthrough — byte-identical to the (modified) source, no compaction.
    expect(parsed.intelligence_brief).toBe(missingRiskFlags);
    expect(parsed.intelligence_brief).not.toContain("(compact)");

    const fallback = (parsed.diagnostics as Diagnostic[]).find(
      d => d.code === "BRIEF_COMPACT_FALLBACK",
    );
    expect(fallback).toBeDefined();
    expect(fallback!.level).toBe("warn");
    expect(fallback!.context).toMatchObject({ missing_section: "## Risk Flags" });
  });
});

// ── R7-b §2 + §3: recent_decisions → 15, guardrails → 20 ────────────────────

describe("R7-b: decision payload caps raised", () => {
  it("recent_decisions returns the LAST 15 of 25 (cap raised from 5)", async () => {
    const handler = await setupBootstrap({ brief: FULL_BRIEF, insights: null, standingRules: null });
    const parsed = await boot(handler);

    expect(parsed.recent_decisions).toHaveLength(15);
    expect(parsed.recent_decisions[0].id).toBe("D-11");
    expect(parsed.recent_decisions[14].id).toBe("D-25");
  });

  it("guardrails returns the first 20 SETTLED of 25 (cap raised from 10)", async () => {
    const handler = await setupBootstrap({ brief: FULL_BRIEF, insights: null, standingRules: null });
    const parsed = await boot(handler);

    expect(parsed.guardrails).toHaveLength(20);
    expect(parsed.guardrails[0].id).toBe("D-1");
    expect(parsed.guardrails[19].id).toBe("D-20");
  });

  it("guardrails excludes non-SETTLED decisions BEFORE applying the 20-cap (mixed-status fixture)", async () => {
    // Metaswarm review (brief-443): the all-SETTLED fixture above cannot
    // detect deletion of the SETTLED filter — this one can. 25 rows with
    // D-2 PENDING, D-5 SUPERSEDED, D-9 OPEN interleaved → 22 SETTLED →
    // guardrails = first 20 SETTLED, ending at D-23.
    const nonSettled: Record<number, string> = { 2: "PENDING", 5: "SUPERSEDED", 9: "OPEN" };
    const mixed =
      "| ID | Title | Domain | Status | Session |\n" +
      "|---|---|---|---|---|\n" +
      Array.from({ length: 25 }, (_, i) => {
        const n = i + 1;
        return `| D-${n} | Decision ${n} | arch | ${nonSettled[n] ?? "SETTLED"} | ${n} |`;
      }).join("\n") +
      "\n\n<!-- EOF: _INDEX.md -->";
    const handler = await setupBootstrap({ brief: FULL_BRIEF, decisions: mixed, insights: null, standingRules: null });
    const parsed = await boot(handler);

    const ids = (parsed.guardrails as Array<{ id: string }>).map(g => g.id);
    expect(ids).toHaveLength(20);
    expect(ids).not.toContain("D-2");
    expect(ids).not.toContain("D-5");
    expect(ids).not.toContain("D-9");
    expect(ids[0]).toBe("D-1");
    expect(ids[19]).toBe("D-23"); // 20th SETTLED row, skipping the three non-SETTLED
    // recent_decisions is intentionally unfiltered — the last 15 of ALL rows.
    expect(parsed.recent_decisions).toHaveLength(15);
    expect((parsed.recent_decisions as Array<{ id: string }>).map(d => d.id)).toContain("D-11");
  });

  it("returns everything when fewer decisions exist than the caps", async () => {
    const small =
      "| ID | Title | Domain | Status | Session |\n" +
      "|---|---|---|---|---|\n" +
      "| D-1 | Only one | arch | SETTLED | 1 |\n\n<!-- EOF: _INDEX.md -->";
    const handler = await setupBootstrap({ brief: FULL_BRIEF, decisions: small, insights: null, standingRules: null });
    const parsed = await boot(handler);

    expect(parsed.recent_decisions).toHaveLength(1);
    expect(parsed.guardrails).toHaveLength(1);
  });
});

// ── R7-b §4: prefetch cap removed ────────────────────────────────────────────

describe("R7-b: QW-4 prefetch hard cap of 2 removed", () => {
  it("a 3-keyword opening message prefetches all 3 distinct documents", async () => {
    const handler = await setupBootstrap({ brief: FULL_BRIEF, insights: null, standingRules: null });
    // keywords: architecture → architecture.md, bug → known-issues.md,
    // task/queue → task-queue.md (3 distinct docs; old cap sliced to 2)
    const parsed = await boot(handler, "fix the architecture bug in the task queue");

    const files = (parsed.prefetched_documents as Array<{ file: string }>).map(d => d.file);
    expect(files).toContain(".prism/architecture.md");
    expect(files).toContain(".prism/known-issues.md");
    expect(files).toContain(".prism/task-queue.md");
    expect(files.length).toBeGreaterThanOrEqual(3);
  });
});

// ── D-253 §Change 1: Tier A bodies only, Tier B+C indexed ───────────────────

describe("D-253: standing-rules delivery — Tier A bodies only, Tier B+C indexed", () => {
  it("delivers ONLY Tier A bodies even with a plain opener (Tier B no longer shipped — D-156 §3.5 restored)", async () => {
    const handler = await setupBootstrap({
      brief: FULL_BRIEF,
      insights: INSIGHTS_WITH_TIER_A,
      standingRules: REGISTRY_B_AND_C,
    });
    const parsed = await boot(handler, "hello there, plain opener with no topical keywords");

    const ids = (parsed.standing_rules as Array<{ id: string }>).map(r => r.id);
    // INS-100 is the lone Tier A rule (from insights.md, union read).
    expect(ids).toEqual(["INS-100"]);
  });

  it("delivers Tier A only on a boot with no opening message at all", async () => {
    const handler = await setupBootstrap({
      brief: FULL_BRIEF,
      insights: INSIGHTS_WITH_TIER_A,
      standingRules: REGISTRY_B_AND_C,
    });
    const parsed = await boot(handler);

    const ids = (parsed.standing_rules as Array<{ id: string }>).map(r => r.id);
    expect(ids).toEqual(["INS-100"]);   // Tier A from insights.md (union read)
    expect(ids).not.toContain("INS-201"); // Tier B no longer in the bodies
    expect(ids).not.toContain("INS-202");
  });

  it("delivered Tier A rules carry their procedure bodies", async () => {
    const handler = await setupBootstrap({
      brief: FULL_BRIEF,
      insights: INSIGHTS_WITH_TIER_A,
      standingRules: REGISTRY_B_AND_C,
    });
    const parsed = await boot(handler);

    const byId = new Map(
      (parsed.standing_rules as Array<{ id: string; procedure: string }>).map(r => [r.id, r]),
    );
    // extractStandingRules takes everything after "**Standing procedure:**"
    // to the end of the ### section — contains, not equals, by design.
    expect(byId.get("INS-100")?.procedure).toContain("Re-read after push.");
  });

  it("standing_rules_index lists Tier B then Tier C entries with id+title+tier+topics (no bodies)", async () => {
    const handler = await setupBootstrap({
      brief: FULL_BRIEF,
      insights: INSIGHTS_WITH_TIER_A,
      standingRules: REGISTRY_B_AND_C,
    });
    const parsed = await boot(handler);

    // Tier B first (source order), then Tier C — union order from the registry.
    expect(parsed.standing_rules_index).toEqual([
      { id: "INS-201", title: "launchd recovery", tier: "B", topics: ["launchd"] },
      { id: "INS-202", title: "untopiced B rule", tier: "B", topics: [] },
      { id: "INS-203", title: "deep audit walkthrough", tier: "C", topics: ["audit"] },
      { id: "INS-204", title: "cost reconciliation", tier: "C", topics: ["cost"] },
    ]);
    // The index carries NO rule bodies (B or C).
    const raw = JSON.stringify(parsed);
    expect(raw).not.toContain("Reload the plist.");
    expect(raw).not.toContain("Long reference body that must NOT ship at boot");
  });

  it("standing_rules_tier_c_index is unchanged: C-only {id,title} back-compat alias", async () => {
    const handler = await setupBootstrap({
      brief: FULL_BRIEF,
      insights: INSIGHTS_WITH_TIER_A,
      standingRules: REGISTRY_B_AND_C,
    });
    const parsed = await boot(handler);

    expect(parsed.standing_rules_tier_c_index).toEqual([
      { id: "INS-203", title: "deep audit walkthrough" },
      { id: "INS-204", title: "cost reconciliation" },
    ]);
    // Alias entries are IDs + titles ONLY — no bodies, no tier/topics.
    for (const entry of parsed.standing_rules_tier_c_index) {
      expect(entry).not.toHaveProperty("procedure");
      expect(entry).not.toHaveProperty("tier");
      expect(entry).not.toHaveProperty("topics");
    }
  });

  it("tier_c index is empty (not absent) when no Tier C rules exist", async () => {
    const handler = await setupBootstrap({
      brief: FULL_BRIEF,
      insights: INSIGHTS_WITH_TIER_A,
      standingRules: null,
    });
    const parsed = await boot(handler);
    expect(parsed.standing_rules_tier_c_index).toEqual([]);
  });

  it("STANDING_RULES_TIERED diagnostic reports the D-253 accounting (tier_b_indexed, Tier B+C indexed)", async () => {
    const handler = await setupBootstrap({
      brief: FULL_BRIEF,
      insights: INSIGHTS_WITH_TIER_A,
      standingRules: REGISTRY_B_AND_C,
    });
    const parsed = await boot(handler);

    const tiered = (parsed.diagnostics as Diagnostic[]).find(d => d.code === "STANDING_RULES_TIERED");
    expect(tiered).toBeDefined();
    expect(tiered!.message).toContain("Tier A bodies; Tier B+C indexed");
    expect(tiered!.context).toMatchObject({
      total: 5,
      delivered: 1,       // A-only
      tier_a: 1,
      tier_b_indexed: 2,  // renamed from tier_b_loaded
      tier_c_indexed: 2,
      from_standing_rules_file: 4,
      from_insights: 1,
    });
    // The deprecated context key is gone.
    expect(tiered!.context).not.toHaveProperty("tier_b_loaded");
  });
});

// ── R-intel-SLO: integration ─────────────────────────────────────────────────

describe("R-intel-SLO: INTEL_SLO diagnostic block", () => {
  it("emits the block with all three metric groups on every bootstrap", async () => {
    const handler = await setupBootstrap({
      brief: FULL_BRIEF,
      insights: INSIGHTS_WITH_TIER_A,
      standingRules: REGISTRY_B_AND_C,
    });
    const parsed = await boot(handler);

    const slo = (parsed.diagnostics as Diagnostic[]).find(d => d.code === "INTEL_SLO");
    expect(slo).toBeDefined();
    expect(slo!.level).toBe("info");
    expect(slo!.context).toMatchObject({
      boot_completeness_percent: 100,
      brief_sections_delivered: 6,
      brief_sections_spec: 6,
      brief_sections_missing: [],
      brief_age_sessions: 1,
      brief_age_target_sessions: 2,
      brief_age_within_target: true,
      continuity_coverage: {
        handoff: true,
        decisions: true,
        insights: true,
        covered: 3,
        total: 3,
      },
    });
  });

  it("reports degraded completeness + coverage when brief/decisions/insights are absent", async () => {
    const handler = await setupBootstrap({
      brief: null,
      insights: null,
      standingRules: null,
      decisions: null,
    });
    const parsed = await boot(handler);

    const slo = (parsed.diagnostics as Diagnostic[]).find(d => d.code === "INTEL_SLO");
    expect(slo).toBeDefined();
    // Delivered: handoff + behavioral rules = 2 of 10 spec items → 20%.
    expect(slo!.context).toMatchObject({
      boot_completeness_percent: 20,
      brief_sections_delivered: 0,
      brief_age_sessions: null,
      brief_age_within_target: null,
      continuity_coverage: {
        handoff: true,
        decisions: false,
        insights: false,
        covered: 1,
        total: 3,
      },
    });
    expect((slo!.context as any).brief_sections_missing).toHaveLength(6);
  });

  it("is log-only: a stale brief breaches the target in INTEL_SLO while BRIEF_STALE still warns independently", async () => {
    const staleBrief = FULL_BRIEF.replace("Last synthesized: S27", "Last synthesized: S24"); // age 4
    const handler = await setupBootstrap({ brief: staleBrief, insights: null, standingRules: null });
    const parsed = await boot(handler);

    const diags = parsed.diagnostics as Diagnostic[];
    const slo = diags.find(d => d.code === "INTEL_SLO");
    expect(slo!.context).toMatchObject({
      brief_age_sessions: 4,
      brief_age_within_target: false,
    });
    // No gating: the response is a normal success and the pre-existing
    // BRIEF_STALE warning fires on its own channel. D-253: the brief is still
    // delivered, now compacted — staleness reads the full preamble independent
    // of compaction, so age is still 4 above.
    expect(diags.find(d => d.code === "BRIEF_STALE")).toBeDefined();
    expect(parsed.intelligence_brief).toContain("(compact)");
    expect(parsed.intelligence_brief.length).toBeLessThan(staleBrief.length);
  });

  it("counts partially-delivered briefs section by section", async () => {
    // Strip two spec sections from the fixture (rename one, drop one).
    const partial = FULL_BRIEF
      .replace("## Recent Trajectory", "## Trajectory (renamed)")
      .replace("## Quality Audit", "## Audit Notes");
    const handler = await setupBootstrap({ brief: partial, insights: null, standingRules: null });
    const parsed = await boot(handler);

    const slo = (parsed.diagnostics as Diagnostic[]).find(d => d.code === "INTEL_SLO");
    expect(slo!.context).toMatchObject({
      brief_sections_delivered: 4,
      // 4 sections + handoff + decisions + behavioral rules = 7 of 10 → 70%
      boot_completeness_percent: 70,
    });
    expect((slo!.context as any).brief_sections_missing).toEqual([
      "## Recent Trajectory",
      "## Quality Audit",
    ]);
  });
});

// ── R-intel-SLO: computeIntelSlo unit tests ──────────────────────────────────

describe("computeIntelSlo (pure computation)", () => {
  const fullInputs = () => ({
    intelligenceBrief: FULL_BRIEF,
    briefAgeSessions: 1,
    handoffPresent: true,
    decisionsPresent: true,
    insightsPresent: true,
    behavioralRulesPresent: true,
  });

  async function loadHelper() {
    const mod = await import("../src/tools/bootstrap.js");
    return mod.computeIntelSlo;
  }

  it("100% when all 6 sections + all 4 fields are delivered", async () => {
    const computeIntelSlo = await loadHelper();
    const slo = computeIntelSlo(fullInputs());
    expect(slo.boot_completeness_percent).toBe(100);
    expect(slo.brief_sections_delivered).toBe(6);
    expect(slo.brief_sections_missing).toEqual([]);
  });

  it("40% when the brief is null but all 4 fields are present", async () => {
    const computeIntelSlo = await loadHelper();
    const slo = computeIntelSlo({ ...fullInputs(), intelligenceBrief: null, briefAgeSessions: null });
    expect(slo.boot_completeness_percent).toBe(40);
    expect(slo.brief_sections_delivered).toBe(0);
    expect(slo.brief_sections_missing).toHaveLength(6);
  });

  it("rounds: 5 sections + 4 fields → 90%; 1 section + 0 fields → 10%", async () => {
    const computeIntelSlo = await loadHelper();
    const fiveSections = FULL_BRIEF.replace("## Quality Audit", "## Audit");
    expect(computeIntelSlo({ ...fullInputs(), intelligenceBrief: fiveSections }).boot_completeness_percent).toBe(90);

    const oneSection = "## Project State\nOnly this.";
    expect(
      computeIntelSlo({
        intelligenceBrief: oneSection,
        briefAgeSessions: null,
        handoffPresent: false,
        decisionsPresent: false,
        insightsPresent: false,
        behavioralRulesPresent: false,
      }).boot_completeness_percent,
    ).toBe(10);
  });

  it("brief_age_within_target: true at the 2-session boundary, false above, null when unknown", async () => {
    const computeIntelSlo = await loadHelper();
    expect(computeIntelSlo({ ...fullInputs(), briefAgeSessions: 2 }).brief_age_within_target).toBe(true);
    expect(computeIntelSlo({ ...fullInputs(), briefAgeSessions: 3 }).brief_age_within_target).toBe(false);
    expect(computeIntelSlo({ ...fullInputs(), briefAgeSessions: 0 }).brief_age_within_target).toBe(true);
    expect(computeIntelSlo({ ...fullInputs(), briefAgeSessions: null }).brief_age_within_target).toBeNull();
  });

  it("continuity coverage tracks each flag independently", async () => {
    const computeIntelSlo = await loadHelper();
    const slo = computeIntelSlo({ ...fullInputs(), decisionsPresent: false });
    expect(slo.continuity_coverage).toEqual({
      handoff: true,
      decisions: false,
      insights: true,
      covered: 2,
      total: 3,
    });
  });

  it("matches sections as literal substrings (a renamed header counts as missing)", async () => {
    const computeIntelSlo = await loadHelper();
    const renamed = FULL_BRIEF.replace("## Risk Flags", "## Risks");
    const slo = computeIntelSlo({ ...fullInputs(), intelligenceBrief: renamed });
    expect(slo.brief_sections_missing).toEqual(["## Risk Flags"]);
  });
});

// ── session_name_line: deterministic session-name string ─────────────────────

describe("session_name_line: server-composed session-name string", () => {
  it("is present and is a string", async () => {
    const handler = await setupBootstrap({ brief: FULL_BRIEF, insights: null, standingRules: null });
    const parsed = await boot(handler);

    expect(parsed).toHaveProperty("session_name_line");
    expect(typeof parsed.session_name_line).toBe("string");
  });

  it("exactly equals the composition of project_display_name, session_number, session_timestamp + CST", async () => {
    const handler = await setupBootstrap({ brief: FULL_BRIEF, insights: null, standingRules: null });
    const parsed = await boot(handler);

    const expected = `${parsed.project_display_name} \u2014 Session ${parsed.session_number}: ${parsed.session_timestamp} CST`;
    expect(parsed.session_name_line).toBe(expected);
  });

  it("contains the em-dash \u2014 (U+2014), not a hyphen or double-dash", async () => {
    const handler = await setupBootstrap({ brief: FULL_BRIEF, insights: null, standingRules: null });
    const parsed = await boot(handler);

    expect(parsed.session_name_line).toContain(" \u2014 ");
    expect(parsed.session_name_line).not.toMatch(/ - /);
    expect(parsed.session_name_line).not.toMatch(/ -- /);
  });

  it("ends with \" CST\"", async () => {
    const handler = await setupBootstrap({ brief: FULL_BRIEF, insights: null, standingRules: null });
    const parsed = await boot(handler);

    expect(parsed.session_name_line).toMatch(/ CST$/);
  });

  it("embedded timestamp is byte-identical to session_timestamp (no second clock read)", async () => {
    const handler = await setupBootstrap({ brief: FULL_BRIEF, insights: null, standingRules: null });
    const parsed = await boot(handler);

    // Extract the timestamp portion: everything after ": " and before " CST"
    const match = (parsed.session_name_line as string).match(/: (.+) CST$/);
    expect(match).not.toBeNull();
    expect(match![1]).toBe(parsed.session_timestamp);
  });
});

// ── Spec constant ↔ synthesis prompt coupling ────────────────────────────────

describe("INTELLIGENCE_BRIEF_SPEC_SECTIONS single source of truth", () => {
  it("every spec section appears verbatim in FINALIZATION_SYNTHESIS_PROMPT", async () => {
    const { INTELLIGENCE_BRIEF_SPEC_SECTIONS } = await import(
      "../src/utils/intelligence-brief-spec.js"
    );
    const { FINALIZATION_SYNTHESIS_PROMPT } = await import("../src/ai/prompts.js");
    expect(INTELLIGENCE_BRIEF_SPEC_SECTIONS).toHaveLength(6);
    for (const section of INTELLIGENCE_BRIEF_SPEC_SECTIONS) {
      expect(FINALIZATION_SYNTHESIS_PROMPT).toContain(section);
    }
  });
});

// ── D-253 §Change 2: in-response oversize tripwire + response_bytes ──────────

describe("D-253: oversize tripwire ships in-response", () => {
  it("an oversized payload exposes response_bytes > 100KB AND a BOOTSTRAP_OVERSIZE diagnostic in the response", async () => {
    const handler = await setupBootstrap({
      brief: FULL_BRIEF,
      insights: null,
      standingRules: OVERSIZE_RULES,
    });
    const parsed = await boot(handler);

    expect(typeof parsed.response_bytes).toBe("number");
    expect(parsed.response_bytes).toBeGreaterThan(100_000);

    // Pre-D-253 this diagnostic was added to the collector AFTER
    // diagnostics.list() was already baked into the response, so it could
    // never appear in any payload — only in Railway logs.
    const oversize = (parsed.diagnostics as Diagnostic[]).find(
      d => d.code === "BOOTSTRAP_OVERSIZE",
    );
    expect(oversize).toBeDefined();
    expect(oversize!.level).toBe("error");
    expect((oversize!.context as { responseBytes: number }).responseBytes).toBeGreaterThan(100_000);
  });

  it("a normal payload exposes response_bytes and emits NO BOOTSTRAP_OVERSIZE", async () => {
    const handler = await setupBootstrap({
      brief: FULL_BRIEF,
      insights: INSIGHTS_WITH_TIER_A,
      standingRules: REGISTRY_B_AND_C,
    });
    const parsed = await boot(handler);

    expect(typeof parsed.response_bytes).toBe("number");
    expect(parsed.response_bytes).toBeLessThan(80_000);
    expect(
      (parsed.diagnostics as Diagnostic[]).find(d => d.code === "BOOTSTRAP_OVERSIZE"),
    ).toBeUndefined();
  });
});

// ── D-253 §Change 3: compactor section names are spec-coupled ────────────────

describe("D-253: compactIntelligenceBrief section names are spec-coupled", () => {
  it("every section the compactor consumes is a member of INTELLIGENCE_BRIEF_SPEC_SECTIONS", async () => {
    const { BRIEF_COMPACT_SECTIONS } = await import("../src/tools/bootstrap.js");
    const { INTELLIGENCE_BRIEF_SPEC_SECTIONS } = await import(
      "../src/utils/intelligence-brief-spec.js"
    );

    // Subset assertion: no compactor section is a string literal divorced from
    // the spec (the INS-249 coupling guard).
    for (const name of Object.values(BRIEF_COMPACT_SECTIONS)) {
      expect(INTELLIGENCE_BRIEF_SPEC_SECTIONS).toContain(name);
    }
    // Extra guard against a silent spec reorder: pin the exact section names
    // the compactor relies on. Test-side literals are fine — the production
    // compactor itself uses none.
    expect(BRIEF_COMPACT_SECTIONS.projectState).toBe("## Project State");
    expect(BRIEF_COMPACT_SECTIONS.riskFlags).toBe("## Risk Flags");
    expect(BRIEF_COMPACT_SECTIONS.qualityAudit).toBe("## Quality Audit");
  });
});
