// M-014 — synthesis cost + content integrity (brief-465 Task C, W3-S6).
// SRV-73 (double-bundle dedup + measured token delta), SRV-89/PRM-23 (registry-
// coupled provenance), SRV-72 (brief spec re-spec'd to the consumed sections).
process.env.GITHUB_PAT = process.env.GITHUB_PAT || "test-dummy-pat";

import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import {
  buildSynthesisUserMessage,
  buildPendingDocUpdatesUserMessage,
  FINALIZATION_SYNTHESIS_PROMPT,
} from "../src/ai/prompts.js";
import { enforceProvenanceHeader } from "../src/ai/synthesize.js";
import { modelDisplayFromId, SYNTHESIS_MODEL_ID } from "../src/models.js";
import { INTELLIGENCE_BRIEF_SPEC_SECTIONS } from "../src/utils/intelligence-brief-spec.js";
import { SYNTHESIS_CHARS_PER_TOKEN } from "../src/config.js";

describe("M-014 SRV-73 — synthesis bundle dedup", () => {
  it("the brief and PDU builders are the SAME function (byte-identical output)", () => {
    // They were CHARACTER-FOR-CHARACTER duplicates; now one implementation.
    expect(buildPendingDocUpdatesUserMessage).toBe(buildSynthesisUserMessage);
    const docs = new Map([["handoff.md", { content: "x".repeat(1000), size: 1000 }]]);
    expect(buildPendingDocUpdatesUserMessage("p", 1, "t", docs)).toBe(
      buildSynthesisUserMessage("p", 1, "t", docs),
    );
  });

  it("measures the per-finalize bundle token cost the dedup eliminates (SRV-73 headline)", () => {
    // A doc map at roughly the audit's measured production scale (~413,658 B).
    const docs = new Map<string, { content: string; size: number }>();
    for (let i = 0; i < 10; i++) {
      const content = "Lorem ipsum dolor sit amet consectetur. ".repeat(1050); // ~42KB
      docs.set(`doc-${i}.md`, { content, size: content.length });
    }
    const bundle = buildSynthesisUserMessage("prism", 167, "06-14-26 12:00:00", docs);
    const bundleTokens = Math.round(bundle.length / SYNTHESIS_CHARS_PER_TOKEN);

    // Before brief-465: the SAME bundle was assembled AND sent TWICE per finalize
    // (brief + PDU). After: assembled ONCE and shared by both calls.
    const before = bundleTokens * 2;
    const after = bundleTokens;
    expect(after).toBeLessThan(before);
    expect(before - after).toBe(bundleTokens);
    // Surface the measured numbers for the PR evidence block.
    // eslint-disable-next-line no-console
    console.log(
      `M-014 measured bundle: ${bundle.length} B ≈ ${bundleTokens} tokens; per-finalize ASSEMBLED before=${before} after=${after} delta=${before - after} tokens`,
    );
  });
});

describe("M-014 SRV-89 / PRM-23 — provenance is registry-coupled, not a hardcoded literal", () => {
  it("src/ai/prompts.ts contains NO hardcoded model-generation literal (missing_test)", () => {
    const source = readFileSync("src/ai/prompts.ts", "utf-8");
    expect(source).not.toMatch(/Opus \d|Sonnet \d|Fable \d/);
  });

  it("modelDisplayFromId derives the display from the model id", () => {
    expect(modelDisplayFromId("claude-fable-5")).toBe("Fable 5");
    expect(modelDisplayFromId("claude-opus-4-8")).toBe("Opus 4.8");
    expect(modelDisplayFromId("claude-sonnet-4-6[1m]")).toBe("Sonnet 4.6");
    expect(modelDisplayFromId(SYNTHESIS_MODEL_ID)).toBe("Opus 4.8");
  });

  it("enforceProvenanceHeader stamps the model used and corrects a stale line", () => {
    const brief = "# Intelligence Brief — prism\n\n> Last synthesized: S167 (t)\n\n## Project State\n…";
    const stamped = enforceProvenanceHeader(brief, "Fable 5");
    expect(stamped).toContain("Generated by Fable 5 at finalization");
    // The provenance line sits immediately above the Last-synthesized line.
    expect(stamped.indexOf("Generated by Fable 5")).toBeLessThan(stamped.indexOf("Last synthesized"));

    const stale = "# X\n\n> AI-synthesized session intelligence. Generated by Opus 4.6 at finalization.\n> Last synthesized: S1 (t)\n";
    const fixed = enforceProvenanceHeader(stale, "Fable 5");
    expect(fixed).toContain("Generated by Fable 5");
    expect(fixed).not.toContain("Opus 4.6");
  });
});

describe("M-014 SRV-72 — brief spec re-spec'd to the consumed sections", () => {
  it("the spec is the 3 boot-delivered sections; the dropped headers are gone from the prompt", () => {
    expect([...INTELLIGENCE_BRIEF_SPEC_SECTIONS]).toEqual([
      "## Project State",
      "## Risk Flags",
      "## Quality Audit",
    ]);
    // The three sections synthesized-then-dropped by boot compaction are no
    // longer mandated as separate H2 sections.
    expect(FINALIZATION_SYNTHESIS_PROMPT).not.toContain("## Standing Rules & Workflows");
    expect(FINALIZATION_SYNTHESIS_PROMPT).not.toContain("## Active Operational Knowledge");
    expect(FINALIZATION_SYNTHESIS_PROMPT).not.toContain("## Recent Trajectory");
    // SRV-27: the prompt no longer demands extraction from the omitted registry.
    expect(FINALIZATION_SYNTHESIS_PROMPT).not.toContain("Extract ALL entries from insights.md");
  });
});
