/**
 * Intelligence synthesis pipeline.
 * Loads all living documents, calls the configured synthesis model
 * (SYNTHESIS_MODEL_ID — the model registry is the single switch, D-254),
 * pushes intelligence-brief.md.
 */

import { pushFile } from "../github/client.js";
import {
  LIVING_DOCUMENT_NAMES,
  computeSynthesisThinkingEnabled,
  SYNTHESIS_ENABLED,
  SYNTHESIS_INPUT_MAX_TOKENS,
  SYNTHESIS_MODEL,
} from "../config.js";
import { modelDisplayFromId } from "../models.js";
import { resolveDocFiles, resolveDocPushPath } from "../utils/doc-resolver.js";
import { logger } from "../utils/logger.js";
import { resolveCallSiteTimeout, synthesize } from "./client.js";
import {
  boundSynthesisInput,
  buildSynthesisDocManifest,
  renderSynthesisInputManifest,
  type SynthesisDocManifestRow,
  type SynthesisInputBudgetReport,
} from "./input-budget.js";
import {
  FINALIZATION_SYNTHESIS_PROMPT,
  PENDING_DOC_UPDATES_PROMPT,
  buildSynthesisUserMessage,
} from "./prompts.js";
import { generateCstTimestamp } from "../utils/banner.js";
import { INTELLIGENCE_BRIEF_SPEC_SECTIONS } from "../utils/intelligence-brief-spec.js";
import {
  getRecentSuccessful,
  recordSynthesisEvent,
} from "./synthesis-tracker.js";

export interface SynthesisOutcome {
  success: boolean;
  bytes_written?: number;
  input_tokens?: number;
  output_tokens?: number;
  error?: string;
  /** brief-445 / R3-dur: pre/post-trim token estimates for the assembled
   *  synthesis input, plus what (if anything) the input bound trimmed.
   *  Present once the input has been assembled — including on failures after
   *  assembly, so a timeout can be correlated with the input size that
   *  produced it. Log-only observability; never an error condition. */
  input_budget?: SynthesisInputBudgetReport;
}

/**
 * Server-stamp the `> Last synthesized: S{N} ({timestamp})` header
 * (brief-456 / SRV-52). Three consumers hang off this one line — bootstrap
 * staleness detection, prism_synthesize status, and apply-pdu's
 * parseLastSynthesizedSession — and it previously existed only as a prompt
 * instruction the model could omit or reformat. Same pattern as the EOF
 * sentinel enforcement: the server already knows sessionNumber + timestamp,
 * so it injects/replaces deterministically before push.
 */
export function enforceLastSynthesizedHeader(
  content: string,
  sessionNumber: number,
  timestamp: string,
): string {
  const canonical = `> Last synthesized: S${sessionNumber} (${timestamp})`;
  const headerRe = /^>\s*Last synthesized:.*$/m;
  if (headerRe.test(content)) {
    return content.replace(headerRe, () => canonical);
  }
  const lines = content.split("\n");
  if (lines[0]?.startsWith("# ")) {
    lines.splice(1, 0, "", canonical);
    return lines.join("\n");
  }
  return `${canonical}\n\n${content}`;
}

/**
 * Server-stamp the `> AI-synthesized session intelligence. Generated by
 * {model} at finalization.` provenance line (brief-465 / SRV-89 / PRM-23). The
 * prompt previously hardcoded "Generated by Opus 4.6" — two model generations
 * stale — so every production brief carried false provenance and the D-254
 * single-switch registry silently missed the literal on each bump. The model
 * name is now stamped from the model ACTUALLY used (derived via
 * modelDisplayFromId), exactly like the EOF sentinel and Last-synthesized
 * header. The line sits immediately above the Last-synthesized line.
 */
export function enforceProvenanceHeader(content: string, modelDisplay: string): string {
  const canonical = `> AI-synthesized session intelligence. Generated by ${modelDisplay} at finalization.`;
  const provRe = /^>\s*AI-synthesized session intelligence\..*$/m;
  if (provRe.test(content)) {
    return content.replace(provRe, () => canonical);
  }
  const lines = content.split("\n");
  const lastIdx = lines.findIndex(l => /^>\s*Last synthesized:/.test(l));
  if (lastIdx !== -1) {
    lines.splice(lastIdx, 0, canonical);
    return lines.join("\n");
  }
  if (lines[0]?.startsWith("# ")) {
    lines.splice(1, 0, "", canonical);
    return lines.join("\n");
  }
  return `${canonical}\n\n${content}`;
}

/**
 * Warn-level SYNTHESIS_FAILED observation emission (brief-456 / SRV-51).
 * Finalize fires synthesis fire-and-forget, so a failure is invisible in the
 * commit response — this log line is the boot-time surfacing channel.
 * Warn level is deliberate: prism_bootstrap's observation gate runs a single
 * Railway query filtered `@level:warn`; an error-level line would never be
 * seen by it. checkSynthesisObservationEvents matches the leading code token
 * and requires the projectSlug attribute.
 */
function emitSynthesisFailed(
  projectSlug: string,
  sessionNumber: number,
  kind: "intelligence_brief" | "pending_updates",
  error: string,
): void {
  logger.warn(`SYNTHESIS_FAILED — background synthesis did not produce a pushed ${kind}`, {
    projectSlug,
    sessionNumber,
    synthesis_kind: kind,
    error,
  });
}

/**
 * The assembled synthesis input bundle — the user message, its trim report, the
 * doc count, and the timestamp it was stamped with. Shared by the
 * intelligence-brief and pending-doc-updates calls so the bundle is built ONCE
 * per finalize (brief-465 / SRV-73).
 */
export interface SynthesisBundle {
  userMessage: string;
  inputBudget: SynthesisInputBudgetReport;
  timestamp: string;
  docCount: number;
  /** brief-s202b T9b: per-doc {path, true_bytes, included_bytes, truncated}
   *  rows — the machine-readable size fact source prepended to the input and
   *  the driver of the truncation provenance footer (T9c). Optional for
   *  hand-built test bundles. */
  docManifest?: SynthesisDocManifestRow[];
}

/** Decision-domain files folded into the synthesis input (D-67 backward-compat). */
const SYNTHESIS_DECISION_DOMAIN_NAMES = [
  "decisions/architecture.md",
  "decisions/operations.md",
  "decisions/optimization.md",
  "decisions/onboarding.md",
  "decisions/integrity.md",
  "decisions/resilience.md",
  "decisions/production-stack.md",
];

/**
 * Assemble the synthesis input bundle ONCE (brief-465 / SRV-73).
 *
 * The intelligence-brief and pending-doc-updates pipelines fetch the SAME doc
 * set (LIVING_DOCUMENT_NAMES minus intelligence-brief.md — pending-doc-updates.md
 * is not a living document) and built a CHARACTER-IDENTICAL ~103K-token bundle,
 * then sent it twice per finalize. This builds that bundle once; finalize passes
 * the result to both calls so the duplicate ~10-doc GitHub fetch and the
 * duplicate assembly no longer happen.
 *
 * Invariant (S40 FINDING-14): archives MUST NOT be synthesis input —
 * LIVING_DOCUMENT_NAMES carries no `-archive.md` entries, so the filter is
 * archive-safe by construction.
 */
export async function assembleSynthesisBundle(
  projectSlug: string,
  sessionNumber: number,
): Promise<SynthesisBundle> {
  const docsToFetch = LIVING_DOCUMENT_NAMES.filter(d => d !== "intelligence-brief.md");
  const docMap = await resolveDocFiles(projectSlug, [...docsToFetch]);

  let domainMap: Map<string, { content: string; size: number }> = new Map();
  try {
    domainMap = await resolveDocFiles(projectSlug, SYNTHESIS_DECISION_DOMAIN_NAMES);
  } catch {
    // Domain files may not all exist — that's fine.
    logger.info("Some decision domain files not found", { projectSlug });
  }

  const allDocs = new Map([...docMap, ...domainMap]);

  // Bound the combined input (brief-445 / R3-dur — durable CS-1 timeout
  // backstop), then build the user message from the bounded doc set. Normal-case
  // inputs (under the ceiling) pass through unchanged; over-ceiling inputs are
  // deterministically priority-trimmed instead of running into SYNTHESIS_TIMEOUT.
  const timestamp = generateCstTimestamp();
  const bounded = boundSynthesisInput(allDocs, (docs) =>
    buildSynthesisUserMessage(projectSlug, sessionNumber, timestamp, docs),
  );

  // brief-s202b T9b (D-278): per-doc size manifest — TRUE sizes as the fact
  // source — prepended to the assembled input for ALL docs. T9d: one
  // SYNTHESIS_INPUT_TRUNCATED info line per truncated doc (the transcript-
  // auditable record that a size claim traceable to a trim is a pipeline
  // artifact, never kill-switch-tripping drift — D-277/INS-370).
  const docManifest = buildSynthesisDocManifest(allDocs, bounded.docs);
  for (const row of docManifest) {
    if (!row.truncated) continue;
    logger.info("SYNTHESIS_INPUT_TRUNCATED", {
      call_site: "synthesis_bundle", // shared CS-2 (brief) + CS-3 (pdu) input
      projectSlug,
      sessionNumber,
      path: row.path,
      true_bytes: row.true_bytes,
      included_bytes: row.included_bytes,
    });
  }

  const userMessage = `${renderSynthesisInputManifest(docManifest)}\n\n${buildSynthesisUserMessage(projectSlug, sessionNumber, timestamp, bounded.docs)}`;
  return {
    userMessage,
    inputBudget: {
      pre_trim_tokens: bounded.pre_trim_tokens,
      post_trim_tokens: bounded.post_trim_tokens,
      trimmed: bounded.trimmed,
      trimmed_docs: bounded.trimmed_docs,
    },
    timestamp,
    docCount: bounded.docs.size,
    docManifest,
  };
}

/**
 * brief-s202b T9c (D-278): server-stamped truncation provenance footer.
 * When any synthesis input doc was truncated, append
 * `> Synthesized from: glossary.md [trimmed 82.0KB→21.0KB], …` immediately
 * above the EOF sentinel — same deterministic server-stamp pattern as the
 * staleness/provenance headers (never model-authored). Replaces any existing
 * footer line (re-runs, or a model echoing one). No truncated inputs → the
 * content is returned unchanged (no footer).
 */
export function appendTruncationProvenanceFooter(
  content: string,
  docManifest: SynthesisDocManifestRow[] | undefined,
): string {
  const footerRe = /^>\s*Synthesized from:.*$\n?/m;
  const truncated = (docManifest ?? []).filter(r => r.truncated);
  if (truncated.length === 0) {
    // Strip a stale/model-echoed footer so an untruncated run never carries one.
    return footerRe.test(content) ? content.replace(footerRe, "") : content;
  }
  const kb = (n: number) => `${(n / 1024).toFixed(1)}KB`;
  const footer = `> Synthesized from: ${truncated
    .map(r => `${r.path} [trimmed ${kb(r.true_bytes)}→${kb(r.included_bytes)}]`)
    .join(", ")}`;
  const withoutExisting = footerRe.test(content) ? content.replace(footerRe, "") : content;
  const eofRe = /^<!--\s*EOF:.*-->\s*$/m;
  const eofMatch = withoutExisting.match(eofRe);
  if (eofMatch && eofMatch.index !== undefined) {
    const head = withoutExisting.slice(0, eofMatch.index).replace(/\s+$/, "");
    const tail = withoutExisting.slice(eofMatch.index);
    return `${head}\n\n${footer}\n\n${tail}`;
  }
  return `${withoutExisting.trimEnd()}\n\n${footer}\n`;
}

/**
 * Generate an intelligence brief for a project.
 * Loads all living documents, synthesizes, pushes result.
 *
 * @param prebuilt brief-465 / SRV-73 — when finalize supplies the shared bundle,
 *   the fetch + bound + assemble is skipped (the bundle is built once for both
 *   the brief and PDU calls). Direct callers omit it and the bundle is assembled
 *   here (back-compat).
 */
export async function generateIntelligenceBrief(
  projectSlug: string,
  sessionNumber: number,
  prebuilt?: SynthesisBundle,
): Promise<SynthesisOutcome> {
  if (!SYNTHESIS_ENABLED) {
    return { success: false, error: "Synthesis disabled — no API key" };
  }

  const start = Date.now();
  // brief-445 / R3-dur: populated once the input is assembled, so every
  // outcome (including failures after assembly) carries the budget report.
  let inputBudget: SynthesisInputBudgetReport | undefined;

  try {
    const bundle = prebuilt ?? (await assembleSynthesisBundle(projectSlug, sessionNumber));
    const { userMessage, timestamp } = bundle;
    inputBudget = bundle.inputBudget;

    logger.info("Synthesis input assembled", {
      projectSlug,
      sessionNumber,
      documentCount: bundle.docCount,
      userMessageBytes: userMessage.length,
      shared_bundle: prebuilt !== undefined, // SRV-73: true when finalize built it once for both calls
      // brief-445 / R3-dur observability: pre/post token estimates + what was
      // trimmed, so an operator can read input headroom straight off the logs.
      pre_trim_tokens: inputBudget.pre_trim_tokens,
      post_trim_tokens: inputBudget.post_trim_tokens,
      input_trimmed: inputBudget.trimmed,
      trimmed_docs: inputBudget.trimmed_docs,
      input_token_ceiling: SYNTHESIS_INPUT_MAX_TOKENS,
    });

    // 3. Call the synthesis model with adaptive thinking (Phase 3a — CS-2).
    //    Fire-and-forget per D-78 so latency overhead is invisible to operator.
    // SRV-61: the per-call-site timeout is resolved from the SINGLE source
    // (resolveCallSiteTimeout) so the transport decision can't drift from
    // resolveCallSiteRouting — cc_subprocess gets the larger CC ceiling, the
    // messages_api path the fire-and-forget baseline.
    const briefTimeoutMs = resolveCallSiteTimeout("brief");

    const result = await synthesize(
      FINALIZATION_SYNTHESIS_PROMPT,
      userMessage,
      undefined,
      briefTimeoutMs,
      undefined,
      computeSynthesisThinkingEnabled("brief"), // Phase 5c: default-on per-call-site thinking switch
      "brief", // brief-424 Phase 3c-B: per-call-site routing (SYNTHESIS_BRIEF_* env vars)
      projectSlug, // brief-419: project tagging for boot-time observation surfacing
    );

    if (!result.success) {
      emitSynthesisFailed(projectSlug, sessionNumber, "intelligence_brief", result.error);
      recordSynthesisEvent({
        project: projectSlug,
        sessionNumber,
        timestamp: new Date().toISOString(),
        success: false,
        error: result.error,
        duration_ms: Date.now() - start,
      });
      return { success: false, error: result.error, input_budget: inputBudget };
    }

    // 4. Validate the response has required sections. The canonical section
    //    list is shared with bootstrap's R-intel-SLO completeness computation
    //    (src/utils/intelligence-brief-spec.ts) — single source per INS-30.
    const missingSections = INTELLIGENCE_BRIEF_SPEC_SECTIONS.filter(s => !result.content.includes(s));
    if (missingSections.length > 0) {
      // brief-456 (SRV-07): a max_tokens-truncated brief that is ALSO missing
      // required sections must not overwrite the previous (good) brief —
      // partial-tolerance only applies to structurally complete output.
      if (result.stop_reason === "max_tokens") {
        const truncError =
          `synthesis truncated (stop_reason=max_tokens) with missing sections: ` +
          `${missingSections.join(", ")} — refusing to overwrite intelligence-brief.md`;
        logger.warn("Synthesis output truncated and incomplete — not pushing", {
          projectSlug,
          sessionNumber,
          missingSections,
        });
        emitSynthesisFailed(projectSlug, sessionNumber, "intelligence_brief", truncError);
        recordSynthesisEvent({
          project: projectSlug,
          sessionNumber,
          timestamp: new Date().toISOString(),
          success: false,
          error: truncError,
          duration_ms: Date.now() - start,
        });
        return { success: false, error: truncError, input_budget: inputBudget };
      }
      logger.warn("Synthesis output missing sections", { missingSections });
      // Still push — partial brief is better than no brief
    }

    // 5. Ensure EOF sentinel
    let content = result.content.trim();
    if (!content.endsWith("<!-- EOF: intelligence-brief.md -->")) {
      content += "\n\n<!-- EOF: intelligence-brief.md -->\n";
    }

    // 5b. Server-stamp the staleness header (brief-456 / SRV-52) and the model
    //     provenance line (brief-465 / SRV-89) — both deterministic, from data
    //     the server already holds, so a model bump never leaves stale text.
    content = enforceLastSynthesizedHeader(content, sessionNumber, timestamp);
    content = enforceProvenanceHeader(content, modelDisplayFromId(result.model ?? SYNTHESIS_MODEL));
    // 5c. brief-s202b T9c (D-278): truncation provenance footer — names every
    //     truncated input so a size-claim artifact is traceable at a glance.
    content = appendTruncationProvenanceFooter(content, bundle.docManifest);

    // 6. Push to project repo (D-67: resolve path)
    const briefPushPath = await resolveDocPushPath(projectSlug, "intelligence-brief.md");
    const briefPush = await pushFile(
      projectSlug,
      briefPushPath,
      content,
      `prism: S${sessionNumber} intelligence brief (auto-synthesized)`
    );
    // pushFile reports HTTP failures as a result shape — a failed push must
    // never be recorded as a successful synthesis (SRV-15): the next
    // bootstrap would serve the previous brief while logs/analytics assert a
    // fresh one was produced.
    if (!briefPush.success) {
      const pushError = `intelligence-brief push failed: ${briefPush.error ?? "unknown error"}`;
      logger.warn("Intelligence brief push failed — recording failed synthesis", {
        projectSlug,
        sessionNumber,
        error: pushError,
        ms: Date.now() - start,
      });
      emitSynthesisFailed(projectSlug, sessionNumber, "intelligence_brief", pushError);
      recordSynthesisEvent({
        project: projectSlug,
        sessionNumber,
        timestamp: new Date().toISOString(),
        success: false,
        error: pushError,
        duration_ms: Date.now() - start,
      });
      return { success: false, error: pushError, input_budget: inputBudget };
    }

    const outcome: SynthesisOutcome = {
      success: true,
      bytes_written: new TextEncoder().encode(content).length,
      input_tokens: result.input_tokens,
      output_tokens: result.output_tokens,
      input_budget: inputBudget,
    };

    logger.info("Intelligence brief generated and pushed", {
      projectSlug,
      sessionNumber,
      ...outcome,
      ms: Date.now() - start,
    });

    // brief-456 (SRV-80): transport/model/output_bytes recorded for parity
    // with the PDU (CS-3) success event — fallback rate and model provenance
    // for the flagship artifact were previously untracked.
    recordSynthesisEvent({
      project: projectSlug,
      sessionNumber,
      timestamp: new Date().toISOString(),
      success: true,
      input_tokens: outcome.input_tokens,
      output_tokens: outcome.output_tokens,
      duration_ms: Date.now() - start,
      transport: result.transport,
      model: result.model,
      output_bytes: outcome.bytes_written,
    });

    return outcome;
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    const duration = Date.now() - start;
    logger.error("Intelligence brief generation failed", {
      projectSlug,
      sessionNumber,
      error: message,
      ms: duration,
    });
    emitSynthesisFailed(projectSlug, sessionNumber, "intelligence_brief", message);

    recordSynthesisEvent({
      project: projectSlug,
      sessionNumber,
      timestamp: new Date().toISOString(),
      success: false,
      error: message,
      duration_ms: duration,
    });

    return { success: false, error: message, input_budget: inputBudget };
  }
}

/**
 * Generate a pending doc-updates proposal for a project (D-156 §3.6, D-155).
 *
 * Parallel in shape to generateIntelligenceBrief: same input bundle, different
 * system prompt, different output file. Fired alongside generateIntelligenceBrief
 * by finalize.ts commit-action via Promise.allSettled — fire-and-forget per
 * INS-178.
 *
 * Excludes both `intelligence-brief.md` AND `pending-doc-updates.md` from input
 * to avoid circular references.
 */
export async function generatePendingDocUpdates(
  projectSlug: string,
  sessionNumber: number,
  prebuilt?: SynthesisBundle,
): Promise<SynthesisOutcome> {
  if (!SYNTHESIS_ENABLED) {
    return { success: false, error: "Synthesis disabled — no API key" };
  }

  const start = Date.now();
  // brief-445 / R3-dur: populated once the input is assembled, so every
  // outcome (including failures after assembly) carries the budget report.
  let inputBudget: SynthesisInputBudgetReport | undefined;

  try {
    // brief-465 / SRV-73: the PDU input bundle is byte-identical to the brief's
    // (same doc set, same builder), so when finalize supplies the shared bundle
    // we reuse it instead of fetching + assembling a second copy. Direct callers
    // omit it and the bundle is assembled here (back-compat).
    const bundle = prebuilt ?? (await assembleSynthesisBundle(projectSlug, sessionNumber));
    const { userMessage, timestamp } = bundle;
    inputBudget = bundle.inputBudget;

    logger.info("Pending doc-updates synthesis input assembled", {
      projectSlug,
      sessionNumber,
      documentCount: bundle.docCount,
      userMessageBytes: userMessage.length,
      shared_bundle: prebuilt !== undefined, // SRV-73: true when finalize built it once for both calls
      // brief-445 / R3-dur observability — mirrors the intelligence-brief log.
      pre_trim_tokens: inputBudget.pre_trim_tokens,
      post_trim_tokens: inputBudget.post_trim_tokens,
      input_trimmed: inputBudget.trimmed,
      trimmed_docs: inputBudget.trimmed_docs,
      input_token_ceiling: SYNTHESIS_INPUT_MAX_TOKENS,
    });

    // 3. Call synthesize with callSite="pdu" so per-call-site routing
    //    (brief-417 Phase 3c-A) can route this through the Claude Code
    //    subprocess path when Railway env opts in. Default behavior (no env
    //    vars set) preserves the SYNTHESIS_MODEL_ID default + Messages API
    //    (the model registry is the single switch, D-254).
    //    Fire-and-forget per D-78 / D-156 so latency overhead is invisible.
    // SRV-61: single-source timeout (see the brief path above).
    const pduTimeoutMs = resolveCallSiteTimeout("pdu");
    const result = await synthesize(
      PENDING_DOC_UPDATES_PROMPT,
      userMessage,
      undefined,
      pduTimeoutMs,
      undefined,
      computeSynthesisThinkingEnabled("pdu"), // Phase 5c: default-on per-call-site thinking switch
      "pdu", // brief-417: per-call-site routing
      projectSlug, // brief-419: project tagging for boot-time observation surfacing
    );

    if (!result.success) {
      emitSynthesisFailed(projectSlug, sessionNumber, "pending_updates", result.error);
      recordSynthesisEvent({
        project: projectSlug,
        sessionNumber,
        timestamp: new Date().toISOString(),
        success: false,
        error: result.error,
        duration_ms: Date.now() - start,
        synthesis_kind: "pending_updates",
      });
      return { success: false, error: result.error, input_budget: inputBudget };
    }

    // 4. Validate response sections — lenient (warn-and-push, don't fail).
    const requiredSections = [
      "## architecture.md",
      "## glossary.md",
      "## insights.md",
      "## No Updates Needed",
    ];
    const missingSections = requiredSections.filter(s => !result.content.includes(s));
    if (missingSections.length > 0) {
      logger.warn("Pending doc-updates output missing sections", { missingSections });
    }

    // 4b. brief-417: programmatic CS-3 quality checks. All warn-and-push,
    //     never fail the synthesis (visibility hint per INS-238). Operator
    //     triages via Railway logs.
    const currentOutputBytes = new TextEncoder().encode(result.content).length;

    // Byte-count baseline: compare against last 5 successful CS-3 outputs.
    // Only meaningful with at least 3 historical samples (skip otherwise to
    // avoid noisy warnings during cold-start / post-deploy windows).
    const recentSuccessful = getRecentSuccessful(projectSlug, 5, "pending_updates");
    const baselineSamples = recentSuccessful
      .map((e) => e.output_bytes)
      .filter((b): b is number => typeof b === "number" && b > 0);
    if (baselineSamples.length >= 3) {
      const baselineMean =
        baselineSamples.reduce((sum, b) => sum + b, 0) / baselineSamples.length;
      const lower = baselineMean * 0.5;
      const upper = baselineMean * 1.5;
      if (currentOutputBytes < lower || currentOutputBytes > upper) {
        logger.warn("CS3_QUALITY_BYTE_COUNT_WARNING", {
          projectSlug,
          sessionNumber,
          current_bytes: currentOutputBytes,
          baseline_mean_bytes: Math.round(baselineMean),
          baseline_n: baselineSamples.length,
          lower_bound: Math.round(lower),
          upper_bound: Math.round(upper),
        });
      }
    }

    // Preamble check: first non-empty line must start with "## " or "**".
    // Anything else suggests prompt-leak preamble like "Sure, here is..." or
    // "I'll generate the following...".
    const trimmed = result.content.replace(/^\s+/, "");
    const firstLine = trimmed.split("\n", 1)[0] ?? "";
    if (!firstLine.startsWith("## ") && !firstLine.startsWith("**") && !firstLine.startsWith("# ")) {
      logger.warn("CS3_QUALITY_PREAMBLE_WARNING", {
        projectSlug,
        sessionNumber,
        first_200_chars: trimmed.slice(0, 200),
      });
    }

    // 5. Ensure EOF sentinel
    let content = result.content.trim();
    if (!content.endsWith("<!-- EOF: pending-doc-updates.md -->")) {
      content += "\n\n<!-- EOF: pending-doc-updates.md -->\n";
    }

    // 5b. Server-stamp the staleness header (brief-456 / SRV-52) — apply-pdu's
    // parseLastSynthesizedSession reads this line.
    content = enforceLastSynthesizedHeader(content, sessionNumber, timestamp);
    // 5c. brief-s202b T9c (D-278): truncation provenance footer (mirrors the
    //     intelligence-brief stamp).
    content = appendTruncationProvenanceFooter(content, bundle.docManifest);

    // 6. Push
    const pushPath = await resolveDocPushPath(projectSlug, "pending-doc-updates.md");
    const pduPush = await pushFile(
      projectSlug,
      pushPath,
      content,
      `prism: S${sessionNumber} pending doc updates (auto-synthesized)`,
    );
    // Same contract as the intelligence-brief push (SRV-15): an HTTP-failed
    // push is a failed synthesis, not a success with stale state on disk.
    if (!pduPush.success) {
      const pushError = `pending-doc-updates push failed: ${pduPush.error ?? "unknown error"}`;
      logger.warn("Pending doc-updates push failed — recording failed synthesis", {
        projectSlug,
        sessionNumber,
        error: pushError,
        ms: Date.now() - start,
      });
      emitSynthesisFailed(projectSlug, sessionNumber, "pending_updates", pushError);
      recordSynthesisEvent({
        project: projectSlug,
        sessionNumber,
        timestamp: new Date().toISOString(),
        success: false,
        error: pushError,
        duration_ms: Date.now() - start,
        synthesis_kind: "pending_updates",
      });
      return { success: false, error: pushError, input_budget: inputBudget };
    }

    const outcome: SynthesisOutcome = {
      success: true,
      bytes_written: new TextEncoder().encode(content).length,
      input_tokens: result.input_tokens,
      output_tokens: result.output_tokens,
      input_budget: inputBudget,
    };

    logger.info("Pending doc-updates generated and pushed", {
      projectSlug,
      sessionNumber,
      ...outcome,
      ms: Date.now() - start,
    });

    // brief-417: capture transport + model for cost/quality analysis.
    // result.transport is set by synthesize() based on which routing path
    // actually completed (cc_subprocess on success, messages_api_fallback
    // when the subprocess attempt failed and we retried via Messages API,
    // or messages_api when the call-site routes directly there).
    recordSynthesisEvent({
      project: projectSlug,
      sessionNumber,
      timestamp: new Date().toISOString(),
      success: true,
      input_tokens: outcome.input_tokens,
      output_tokens: outcome.output_tokens,
      duration_ms: Date.now() - start,
      synthesis_kind: "pending_updates",
      transport: result.transport,
      model: result.model,
      output_bytes: currentOutputBytes,
    });

    return outcome;
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    const duration = Date.now() - start;
    logger.error("Pending doc-updates generation failed", {
      projectSlug,
      sessionNumber,
      error: message,
      ms: duration,
    });
    emitSynthesisFailed(projectSlug, sessionNumber, "pending_updates", message);

    recordSynthesisEvent({
      project: projectSlug,
      sessionNumber,
      timestamp: new Date().toISOString(),
      success: false,
      error: message,
      duration_ms: duration,
      synthesis_kind: "pending_updates",
    });

    return { success: false, error: message, input_budget: inputBudget };
  }
}
